name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: rajasekhar-gundala/multi-tenant/payload
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        dockerfile: Dockerfile
        workdir: mySubDirectory
        buildoptions: "--compress --force-rm"
        platforms: linux/amd64,linux/arm64
        tags: "latest,${{ steps.pre-step.outputs.release-version }}"
