name: Build-Scan-Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BuildNumber: ${{ github.run_id }}-${{ github.run_number }}
  ImageName: 'tuneitme/caddyserver'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

- name: Build Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubPassword }}
        repository: ${{ env.ImageName }}
        tags: 'github-${{ env.BuildNumber }}'
        path: '/'
        dockerfile: '/Dockerfile'
        push: false
- name: Trivy Scan - Unknown, Low and Medium Severity
      uses: aquasecurity/trivy-action@0.0.7
      with:
        image-ref: ${{ env.ImageName }}:github-${{ env.BuildNumber }}
        exit-code: 0
        severity: UNKNOWN,LOW,MEDIUM
        
    - name: Trivy Scan - High and Critical Severity
      uses: aquasecurity/trivy-action@0.0.7
      with:        
        image-ref: ${{ env.ImageName }}:github-${{ env.BuildNumber }}
        exit-code: 1
        severity: HIGH,CRITICAL
- name: Push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DockerHubUser }}
        password: ${{ secrets.DockerHubPassword }}
        repository: ${{ env.ImageName }}
        tags: 'github-${{ env.BuildNumber }}'
        path: '/'
        dockerfile: '/Dockerfile'
        push: true
